#!/bin/bash
#
# Selects patients generated by Synthea that have certain cancers.

for F in `\ls output/fhir/*.json`
do

     # Lung Cancer: SNOMED CT codes for NSCLC diagnosis.
#    egrep -li -e 162573006 -e 254637007 -e 424132000 $F > /dev/null

    # Breast Cancer with HER2 biomarker.
    # TODO: add more biomarkers, if desired.
    egrep -li -e 254837009 -e HER2 -e 385798007 $F > /dev/null
    if [ $? -eq 0 ]
    then
        ls -lah $F
        cp $F selected
    fi
done
